[package]
name = "diff-match-patch-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde      = { version = "1", features = ["derive"] }
serde_repr = { version = "0" }

[dev-dependencies]
criterion = "0"
serde_json = "1"

[[bench]]
name = "prefix"
harness = false