[package]
name = "diff-match-patch-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
percent-encoding = "2"
serde            = { version = "1", features = ["derive"], optional = true }
serde_repr       = { version = "0", optional = true }

[features]
serde = ["dep:serde", "dep:serde_repr"]
default = ["serde"]

[dev-dependencies]
criterion = "0"
serde_json = "1"

[[bench]]
name = "prefix"
harness = false